version: "3.4"

services:
  homeassistant:
    build: .
    ports:
      - target: 8123
        published: 8123
        protocol: tcp
    volumes:
        - homeassistant_config:/config

volumes:
    homeassistant_config:
