services:
  python:
    container_name: python
    build:
      context: ./
      dockerfile: .docker/python/Dockerfile

  homeassistant:
    container_name: homeassistant
    build:
      context: ./
      dockerfile: .docker/homeassistant/Dockerfile
    restart: unless-stopped
    privileged: true
    develop:
      watch:
        - action: sync
          path: ./custom_components/ktw_its
          target: /config/custom_components/ktw_its
    ports:
      - 8123:8123
    volumes:
      - homeassistant-config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro

volumes:
  homeassistant-config:
