services:
#  python:
#    container_name: python
#    build:
#      context: ./
#      dockerfile: .docker/python/Dockerfile

  homeassistant:
    container_name: homeassistant
    build:
      context: ./
      dockerfile: .docker/homeassistant/Dockerfile
    restart: unless-stopped
    privileged: false
    develop:
      watch:
        - action: rebuild
          path: ./custom_components/ktw_its
          target: /config/custom_components/ktw_its
    ports:
      - 8123:8123
    volumes:
      - homeassistant-config:/config
      - ./custom_components/ktw_its:/config/custom_components/ktw_its
volumes:
  homeassistant-config:
